// AUTH
export const REDIRECT = 'REDIRECT';
export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const LOGOUT = 'LOGOUT';
export const FETCH_USER = 'FETCH_USER';
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED';
export const REGISTER_PAGE_UNLOADED = 'REGISTER_PAGE_UNLOADED';
export const ASYNC_START = 'ASYNC_START';
export const UPDATE_FIELD_AUTH  = 'UPDATE_FIELD_AUTH';

// COMMON
export const APP_LOAD = 'APP_LOAD';

// PROFILES
export const GET_CURRENT_USER_PROFILE = 'GET_CURRENT_USER_PROFILE';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';

// STATS/DASHBOARD
export const DASHBOARD_UNLOADED = 'DASHBOARD_UNLOADED';
export const ADD_GOAL = 'ADD_GOAL';
export const ADD_ASSIST = 'ADD_ASSIST';
export const GET_STATS = 'GET_STATS';
export const UPDATE_STATS = 'UPDATE_STATS';